

version: 1
updates:

  #mailkit
  - package-ecosystem: "nuget"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"